# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

timeoutInMinutes: 240
pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: sudo apt -y update && sudo apt -y install wget autoconf build-essential libcurl4-gnutls-dev libglib2.0-dev libgdk-pixbuf2.0-dev libgtkglext1-dev libatk1.0-dev libcairo2-dev libtool libxml2-dev libxss-dev libgconf2-dev default-jre qt5-qmake qt5-default  p7zip-full git subversion
  displayName: Install Dependencies

- script: cd Common/3dParty && ./make.sh
  displayName: Build 3dParty

- script: make
  displayName: Build Core
